/* Model-eval layer over the committed CasADi-generated r5 functions
 * under model/generated/ (regenerated by model/gen_model.py from
 * formulation.py).
 *
 * THE WORK-ARRAY RULE (CUSTOM-SOLVER-PLAN.md section 5, verified): generated
 * wrappers use scratch arg/res slots beyond the declared inputs — arg/res/
 * iw/w MUST be sized per each function's _work() query, never per n_in/n_out.
 * cs_model_init() queries _work() for every registered function, takes the
 * maxima, and carves the shared call buffers from the caller's arena once;
 * no allocation ever happens on the call path.
 *
 * Matrix layout: dense COLUMN-MAJOR (CasADi convention). Sx is nx*nx, Sw and
 * Swdot are nx*(nu+1) with forward directions w = [u; T]; A is nx*nx, B is
 * nx*nu, Jx is nh*nx, Ju is nh*nu.
 *
 * All eval functions return CS_OK or a CS_ERR_* status (cs_types.h). */
#ifndef CS_MODEL_H
#define CS_MODEL_H

#include "cs_types.h"

/* ABI guard for the ctypes binding (plan section 2.2). Bump on any change to
 * the exported signatures or layouts. 2 = M1 (cs_solver_* surface added);
 * 3 = M1.1 progress-gate + M2 free-boundary; 4 = M1.2 elastic corridor slacks
 * live in rh mode (cs_solver_set_soft_corr) + the cs_solver_get_qp dump;
 * 5 = M1.4/M1.5 (soft weights, eta box, T_MIN 0.2); 6 = G0.2 runtime
 * row-spacing shift (cs_solver_set_row_offset) + the cs_rh receding-horizon
 * wrapper layer (cs_rh.h). */
#define CS_ABI_VERSION 6

int cs_abi_version(void);
int cs_real_size(void);                      /* sizeof(cs_real): 8=f64, 4=f32 */
void cs_model_dims(int *nx, int *nu, int *nh);

/* N variants compiled into this library (model/generated/turn_r5_N*.c). */
int cs_model_num_variants(void);
int cs_model_variant_N(int i);

/* Arena bytes cs_model_init needs (work maxima + alignment slack). */
size_t cs_model_min_arena(void);

/* Carve the shared call buffers from mem[0..size). Fixed afterwards. */
int cs_model_init(void *mem, size_t size);

/* The _work() maxima actually allocated (after init). */
int cs_model_work(int *sz_arg, int *sz_res, int *sz_iw, int *sz_w);

/* xdot = T*f(x,u)  — tau-domain ODE (pass T=1 for physical time) */
int cs_ode(const cs_real *x, const cs_real *u, const cs_real *T,
           cs_real *xdot);

/* forward VDE of the tau dynamics: Sxdot = Jx*Sx, Swdot = Jx*Sw + [Ju, f] */
int cs_vde_forw(const cs_real *x, const cs_real *Sx, const cs_real *Sw,
                const cs_real *u, const cs_real *T,
                cs_real *xdot, cs_real *Sxdot, cs_real *Swdot);

/* h rows: [jerk_sq, chi, eta - apI(xi), eta - reI(xi), xi] (acados order) */
int cs_h(const cs_real *x, const cs_real *u, cs_real *h);
int cs_h_jac(const cs_real *x, const cs_real *u,
             cs_real *h, cs_real *Jx, cs_real *Ju);

/* one discrete RK4 step of T*f over h = 1/N; N in the compiled variant set */
int cs_step(int N, const cs_real *x, const cs_real *u, const cs_real *T,
            cs_real *x_next);
int cs_step_jac(int N, const cs_real *x, const cs_real *u, const cs_real *T,
                cs_real *x_next, cs_real *A, cs_real *B, cs_real *bT);

#endif /* CS_MODEL_H */
