#!/usr/bin/env python3

def build(bld):
    vehicle = bld.path.name
    bld.ap_stlib(
        name=vehicle + '_libs',
        ap_vehicle=vehicle,
        ap_libraries=bld.ap_common_vehicle_libraries() + [
            'AC_AttitudeControl',
            'AC_CustomControl',
            'AC_InputManager',
            'AC_PrecLand',
            'AC_Sprayer',
            'AC_Autorotation',
            'AC_WPNav',
            'AP_Camera',
            'AP_IRLock',
            'AP_Motors',
            'AP_Avoidance',
            'AP_AdvancedFailsafe',
            'AP_SmartRTL',
            'AP_WheelEncoder',
            'AP_Winch',
            'AP_LTM_Telem',
            'AP_Devo_Telem',
            'AC_AutoTune',
            'AP_KDECAN',
            'AP_SurfaceDistance',
            # onboard turn-MPC: AP_MPCSolver class + the vendored csolver C
            # core, compiled through the per-file mpc_build_*.c wrapper TUs
            # (f32 flight config; see AP_MPCSolver/mpc_cs_defs.h and
            # scripts/mpc/csolver/sync_firmware.sh)
            'AP_MPCSolver',
            # the certified anytime MPC solved ONBOARD: AP_BSolver class +
            # the vendored bsolver C core (f64; see AP_BSolver/AP_BSolver.h
            # and scripts/mpc/bsolver/sync_firmware.sh).  Mutually exclusive
            # with AP_MPCSolver at build time -- the two do not fit together
            # on the target (614 kB against 507 kB free heap).
            'AP_BSolver'
        ],
    )

    bld.ap_program(
        program_name='arducopter',
        program_groups=['bin', 'copter'],
        use=vehicle + '_libs',
        defines=['FRAME_CONFIG=MULTICOPTER_FRAME'],
        )

    bld.ap_program(
        program_name='arducopter-heli',
        program_groups=['bin', 'heli'],
        use=vehicle + '_libs',
        defines=['FRAME_CONFIG=HELI_FRAME'],
        )
